import { Injectable, Logger, NotFoundException, Inject, forwardRef } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { CreatePlaybookDto } from './dto/create-playbook.dto';
import { UpdatePlaybookDto } from './dto/update-playbook.dto';
import { Severity, CaseStatus } from '@prisma/client';
import { SiemPushService } from '../siem/siem-push.service';

@Injectable()
export class PlaybooksService {
  private readonly logger = new Logger(PlaybooksService.name);

  constructor(
    private prisma: PrismaService,
    @Inject(forwardRef(() => SiemPushService))
    private siemPushService: SiemPushService,
  ) {}

  async create(createPlaybookDto: CreatePlaybookDto) {
    return this.prisma.playbook.create({
      data: createPlaybookDto as any,
    });
  }

  async findAll() {
    return this.prisma.playbook.findMany({
      orderBy: { createdAt: 'desc' },
      include: {
        _count: {
          select: { executions: true },
        },
      },
    });
  }

  async findOne(id: string) {
    const playbook = await this.prisma.playbook.findUnique({
      where: { id },
      include: { executions: { take: 20, orderBy: { executedAt: 'desc' } } },
    });
    if (!playbook) {
      throw new NotFoundException(`Playbook with ID ${id} not found`);
    }
    return playbook;
  }

  async update(id: string, updatePlaybookDto: UpdatePlaybookDto) {
    await this.findOne(id);
    return this.prisma.playbook.update({
      where: { id },
      data: updatePlaybookDto as any,
    });
  }

  async remove(id: string) {
    await this.findOne(id);
    return this.prisma.playbook.delete({
      where: { id },
    });
  }

  async getExecutionHistory() {
    return this.prisma.playbookExecution.findMany({
      orderBy: { executedAt: 'desc' },
      take: 100,
      include: {
        playbook: { select: { id: true, name: true } },
        alert: { select: { id: true, description: true, severity: true, source: true } },
      },
    });
  }

  async evaluateAndExecuteForAlert(alert: any) {
    try {
      const enabledPlaybooks = await this.prisma.playbook.findMany({
        where: { enabled: true },
      });

      for (const playbook of enabledPlaybooks) {
        const isMatch = this.checkTriggerCondition(playbook.triggerCondition, alert);
        if (isMatch) {
          await this.executePlaybook(playbook, alert);
        }
      }
    } catch (err: any) {
      this.logger.error(`Error evaluating playbooks for Alert ${alert.id}: ${err.message}`, err.stack);
    }
  }

  private checkTriggerCondition(condition: any, alert: any): boolean {
    if (!condition) return false;

    if (condition.severity && condition.severity !== alert.severity) {
      return false;
    }

    if (condition.minScore && alert.score < condition.minScore) {
      return false;
    }

    if (condition.source && !alert.source?.toLowerCase().includes(condition.source.toLowerCase())) {
      return false;
    }

    if (condition.ruleType && alert.rule?.correlationType !== condition.ruleType) {
      return false;
    }

    return true;
  }

  private async executePlaybook(playbook: any, alert: any) {
    this.logger.log(`[SOAR PLAYBOOK] Firing Playbook '${playbook.name}' for Alert #${alert.id}`);
    const actionsRan: any[] = [];
    let overallSuccess = true;

    const actions = (playbook.actions as any[]) || [];

    for (const action of actions) {
      const stepLog: any = { action: action.type, startedAt: new Date().toISOString() };
      try {
        switch (action.type) {
          case 'CREATE_CASE': {
            // Auto-create a Case if alert is not already linked to a case
            let caseId = alert.relatedCaseId;
            if (!caseId) {
              const newCase = await this.prisma.case.create({
                data: {
                  title: `[SOAR Auto-Case] ${alert.description}`,
                  description: `Automated Incident Case generated by SOAR Playbook '${playbook.name}' for Alert #${alert.id}. Source: ${alert.source}`,
                  severity: alert.severity,
                  status: CaseStatus.OPEN,
                },
              });
              caseId = newCase.id;

              // Link alert to case
              await this.prisma.alert.update({
                where: { id: alert.id },
                data: { relatedCaseId: caseId },
              });
            }
            stepLog.status = 'SUCCESS';
            stepLog.details = `Created/Linked Case #${caseId}`;
            break;
          }

          case 'ESCALATE_SEVERITY': {
            const newSev = (action.targetSeverity || Severity.CRITICAL) as Severity;
            await this.prisma.alert.update({
              where: { id: alert.id },
              data: { severity: newSev },
            });
            stepLog.status = 'SUCCESS';
            stepLog.details = `Escalated severity to ${newSev}`;
            break;
          }

          case 'ASSIGN_ANALYST': {
            // Assign to round-robin or designated user
            let assigneeId = action.assigneeId;
            if (!assigneeId) {
              const analyst = await this.prisma.user.findFirst({
                where: { role: { in: ['SOC_ANALYST', 'INVESTIGATOR', 'ADMIN'] } },
              });
              assigneeId = analyst?.id;
            }

            if (assigneeId && alert.relatedCaseId) {
              await this.prisma.case.update({
                where: { id: alert.relatedCaseId },
                data: { assignedToId: assigneeId },
              });
              stepLog.status = 'SUCCESS';
              stepLog.details = `Assigned Case to User #${assigneeId}`;
            } else {
              stepLog.status = 'SUCCESS';
              stepLog.details = `No Case linked yet or no analyst available`;
            }
            break;
          }

          case 'FORWARD_SIEM': {
            if (this.siemPushService) {
              await this.siemPushService.pushAlertToSiem(alert);
              stepLog.status = 'SUCCESS';
              stepLog.details = 'Pushed alert to configured SIEM endpoints (Splunk/Wazuh)';
            } else {
              stepLog.status = 'SKIPPED';
              stepLog.details = 'SIEM push service unavailable';
            }
            break;
          }

          default:
            stepLog.status = 'SKIPPED';
            stepLog.details = `Unknown action type ${action.type}`;
        }
      } catch (err: any) {
        overallSuccess = false;
        stepLog.status = 'FAILED';
        stepLog.error = err.message;
      }
      stepLog.finishedAt = new Date().toISOString();
      actionsRan.push(stepLog);
    }

    // Save execution record
    await this.prisma.playbookExecution.create({
      data: {
        playbookId: playbook.id,
        alertId: alert.id,
        actionsRan,
        status: overallSuccess ? 'SUCCESS' : 'PARTIAL',
      },
    });

    this.logger.log(`[SOAR PLAYBOOK] Finished '${playbook.name}' Execution with status: ${overallSuccess ? 'SUCCESS' : 'PARTIAL'}`);
  }
}
