import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { PrismaService } from './prisma/prisma.service';
import { PlaybooksService } from './playbooks/playbooks.service';
import { DetectionEngineService } from './detection-engine/detection-engine.service';
import { SiemPushService } from './siem/siem-push.service';
import { MalwareService } from './malware/malware.service';
import { EmailAlertService } from './common/email-alert.service';
import { Taxii2Service } from './taxii2/taxii2.service';
import { CasesService } from './cases/cases.service';
import { Severity, RuleCorrelationType, CaseStatus } from '@prisma/client';
import { startSiemDevServers } from './siem-dev-listener';

async function runPhase7Verification() {
  console.log('================================================================');
  console.log('  NATIONAL CYBER THREAT INTEL PLATFORM — PHASE 7 VERIFICATION   ');
  console.log('================================================================\n');

  // Start Live SIEM Dev Collector Listener (Splunk HEC :8088 & Wazuh :55000)
  const siemServers = startSiemDevServers();
  await new Promise((resolve) => setTimeout(resolve, 500));

  const app = await NestFactory.createApplicationContext(AppModule, { logger: false });
  const prisma = app.get(PrismaService);
  const playbooksService = app.get(PlaybooksService);
  const detectionEngine = app.get(DetectionEngineService);
  const siemPushService = app.get(SiemPushService);
  const malwareService = app.get(MalwareService);
  const emailAlertService = app.get(EmailAlertService);
  const taxii2Service = app.get(Taxii2Service);
  const casesService = app.get(CasesService);

  let passedTests = 0;
  let totalTests = 6;

  try {
    // -------------------------------------------------------------------------
    // TEST 1: SOAR Automated Response Playbooks
    // -------------------------------------------------------------------------
    console.log('\n📌 [TEST 1/6] SOAR Automated Response Playbooks & Trigger Engine');
    
    // Seed test playbook
    const playbook = await prisma.playbook.upsert({
      where: { name: 'Auto-Case & Escalate Playbook' },
      update: { enabled: true },
      create: {
        name: 'Auto-Case & Escalate Playbook',
        description: 'Auto-create investigation case and escalate severity for critical IOC detections',
        triggerCondition: { severity: 'HIGH' },
        actions: [
          { type: 'CREATE_CASE' },
          { type: 'ESCALATE_SEVERITY', targetSeverity: 'CRITICAL' },
          { type: 'ASSIGN_ANALYST' },
          { type: 'FORWARD_SIEM' },
        ],
        enabled: true,
      },
    });

    // Seed test detection rule
    const rule = await prisma.detectionRule.upsert({
      where: { name: 'Phase7 High Threat Test Rule' },
      update: { enabled: true },
      create: {
        name: 'Phase7 High Threat Test Rule',
        description: 'Triggers on C2 tag',
        condition: { type: 'MATCH_TAGS', tags: ['c2-server', 'phase7-test'] },
        severity: Severity.HIGH,
        correlationType: RuleCorrelationType.SIMPLE,
        enabled: true,
      },
    });

    // Seed test IOC
    const ioc = await prisma.ioc.upsert({
      where: { value: '198.51.100.77' },
      update: { tags: ['c2-server', 'phase7-test'] },
      create: {
        type: 'IP',
        value: '198.51.100.77',
        source: 'AlienVaultOTX',
        tags: ['c2-server', 'phase7-test'],
      },
    });

    // Evaluate Detection Rule (which triggers SOAR Playbook)
    await detectionEngine.evaluateIoc(ioc.id);

    // Verify Alert was created & escalation executed
    const generatedAlert = await prisma.alert.findFirst({
      where: { sourceIocId: ioc.id, ruleId: rule.id },
    });

    if (!generatedAlert) {
      throw new Error('FAILED: Alert was not generated by detection engine');
    }

    // Verify Playbook Execution Log
    const execution = await prisma.playbookExecution.findFirst({
      where: { alertId: generatedAlert.id, playbookId: playbook.id },
    });

    if (execution && (execution.status === 'SUCCESS' || execution.status === 'PARTIAL')) {
      console.log(`  ✅ Playbook '${playbook.name}' Fired Automatically! Execution Status: ${execution.status}`);
      console.log(`     Alert #${generatedAlert.id.slice(0, 8)} Escalated Severity: ${generatedAlert.severity}`);
      console.log(`     Actions Executed: ${JSON.stringify(execution.actionsRan)}\n`);
      passedTests++;
    } else {
      console.log(`  ⚠️ Playbook execution log check failed\n`);
    }

    // -------------------------------------------------------------------------
    // TEST 2: Live SIEM Push Integrations (Splunk HEC & Wazuh)
    // -------------------------------------------------------------------------
    console.log('📌 [TEST 2/6] Live SIEM Push Integrations (Splunk HEC & Wazuh Manager)');
    const pushResult = await siemPushService.pushAlertToSiem(generatedAlert);
    
    if (pushResult.splunkStatus.includes('200 OK') && pushResult.wazuhStatus.includes('200 OK')) {
      console.log(`  ✅ Splunk HEC Endpoint: ${pushResult.splunkStatus}`);
      console.log(`     Splunk HEC Response Body: ${JSON.stringify(pushResult.splunkResponseBody)}`);
      console.log(`  ✅ Wazuh Manager API Endpoint: ${pushResult.wazuhStatus}`);
      console.log(`     Wazuh API Response Body: ${JSON.stringify(pushResult.wazuhResponseBody)}\n`);
      passedTests++;
    } else {
      console.log(`  ❌ SIEM Push Execution Failed: Splunk=${pushResult.splunkStatus}, Wazuh=${pushResult.wazuhStatus}\n`);
    }

    // -------------------------------------------------------------------------
    // TEST 3: VirusTotal Malware Reputation Scanning
    // -------------------------------------------------------------------------
    console.log('📌 [TEST 3/6] VirusTotal Malware Reputation Scan (API v3 / Reputation Engine)');
    
    const sample = await prisma.malwareSample.upsert({
      where: { hashSha256: '2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae' },
      update: {},
      create: {
        name: 'Phase7_Test_Trojan.exe',
        malwareFamily: 'CobaltStrike',
        hashSha256: '2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae',
        fileType: 'Win32 EXE',
        source: 'abuse.ch MalwareBazaar',
        tags: ['cobalt-strike', 'beacon', 'phase7'],
      },
    });

    const vtResult = await malwareService.scanWithVirusTotal(sample.id);
    if (vtResult.vtScanResult) {
      console.log(`  ✅ VirusTotal Scan Verdict: ${(vtResult.vtScanResult as any).verdict}`);
      console.log(`     Detection Ratio: ${(vtResult.vtScanResult as any).detectionRatio}`);
      console.log(`     Top Vendor Verdicts: ${JSON.stringify((vtResult.vtScanResult as any).vendorVerdicts)}\n`);
      passedTests++;
    } else {
      throw new Error('FAILED: VirusTotal scan result was not stored');
    }

    // -------------------------------------------------------------------------
    // TEST 4: Email Alerting (Brevo SMTP)
    // -------------------------------------------------------------------------
    console.log('📌 [TEST 4/6] Transactional Email Alerting (Brevo SMTP)');
    const emailResult = await emailAlertService.sendCriticalAlertEmail(generatedAlert);
    if (emailResult.sent) {
      console.log(`  ✅ Brevo SMTP Dispatch SUCCESS: ${emailResult.message}`);
      console.log(`     Target Admin/Investigator Recipients: ${emailResult.recipientCount}\n`);
      passedTests++;
    } else {
      console.log(`  ⚠️ Brevo SMTP Status: PENDING CREDENTIALS (${emailResult.message})`);
      console.log(`     Target Recipients Found: ${emailResult.recipientCount}\n`);
    }

    // -------------------------------------------------------------------------
    // TEST 5: STIX / TAXII 2.1 Server & Normalizer
    // -------------------------------------------------------------------------
    console.log('📌 [TEST 5/6] STIX 2.1 / TAXII 2.1 Server Normalizer');
    const discovery = taxii2Service.getDiscovery();
    const collections = taxii2Service.getCollections();
    const stixBundle = await taxii2Service.getCollectionObjects('ctp-indicators');

    console.log(`  ✅ TAXII 2.1 Discovery Title: '${discovery.title}'`);
    console.log(`  ✅ TAXII 2.1 Collections Count: ${collections.collections.length}`);
    console.log(`  ✅ STIX 2.1 Bundle Generated! Type: '${stixBundle.type}', Version: '${stixBundle.spec_version}', Objects Count: ${stixBundle.objects.length}`);
    console.log(`     Sample STIX Indicator SDO: ${JSON.stringify(stixBundle.objects[0])}\n`);
    passedTests++;

    // -------------------------------------------------------------------------
    // TEST 6: Dual-Audience AI Incident Report Generation
    // -------------------------------------------------------------------------
    console.log('📌 [TEST 6/6] Full AI-Generated Dual-Audience Incident Report (Groq LLM)');
    
    const testCase = await prisma.case.create({
      data: {
        title: 'Phase 7 APT Ransomware Investigation',
        description: 'Multi-vector attack targeting government network infrastructure',
        severity: Severity.CRITICAL,
        status: CaseStatus.OPEN,
      },
    });

    const reportCase = await casesService.generateIncidentReport(testCase.id);
    const report = reportCase.report;

    if (report && report.executiveSummary && report.technicalDetails) {
      console.log(`  ✅ Incident Report Successfully Generated via ${report.modelUsed}!`);
      console.log(`     👔 Executive Briefing Length: ${report.executiveSummary.length} chars`);
      console.log(`     🛠️ Technical Deep-Dive Length: ${report.technicalDetails.length} chars\n`);
      passedTests++;
    } else {
      throw new Error('FAILED: Incident report did not generate expected fields');
    }

    console.log('================================================================');
    console.log(`  PHASE 7 VERIFICATION COMPLETE: ${passedTests}/${totalTests} TESTS PASSED  `);
    console.log('================================================================');

  } catch (err: any) {
    console.error('❌ Verification Error:', err.message, err.stack);
  } finally {
    siemServers.splunkServer.close();
    siemServers.wazuhServer.close();
    await app.close();
  }
}

runPhase7Verification();
